export const SAVE_USER_LOGIN_CRED = "SAVE_CRED";
export const UPDATE_USER_LOGIN_CRED = "UPDATE_CRED";
export const REMOVE_USER_LOGIN_CRED = "REMOVE_CRED";

export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const REMOVE_USER_DETAILS = "REMOVE_USER_DETAILS";

export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";
