import { statesAndCityListIndiaDataType } from "..";

export const statesListIndia: Array<statesAndCityListIndiaDataType> = [
  {
    key: 1,
    value: "AN",
    label: "Andaman and Nicobar Islands",
    // value: "Andaman and Nicobar Islands",
  },
  {
    key: 2,
    value: "AP",
    label: "Andhra Pradesh",
    // value: "Andhra Pradesh",
  },
  {
    key: 3,
    value: "AR",
    label: "Arunachal Pradesh",
    // value: "Arunachal Pradesh",
  },
  {
    key: 4,
    value: "AS",
    label: "Assam",
    // value: "Assam",
  },
  {
    key: 5,
    value: "BR",
    label: "Bihar",
    // value: "Bihar",
  },
  {
    key: 6,
    value: "CG",
    label: "Chandigarh",
    // value: "Chandigarh",
  },
  {
    key: 7,
    value: "CH",
    label: "Chhattisgarh",
    // value: "Chhattisgarh",
  },
  {
    key: 8,
    value: "DN",
    label: "Dadra and Nagar Haveli",
    // value: "Dadra and Nagar Haveli",
  },
  {
    key: 9,
    value: "DD",
    label: "Daman and Diu",
    // value: "Daman and Diu",
  },
  {
    key: 10,
    value: "DL",
    label: "Delhi",
    // value: "Delhi",
  },
  {
    key: 11,
    value: "GA",
    label: "Goa",
    // value: "Goa",
  },
  {
    key: 12,
    value: "GJ",
    label: "Gujarat",
    // value: "Gujarat",
  },
  {
    key: 13,
    value: "HR",
    label: "Haryana",
    // value: "Haryana",
  },
  {
    key: 14,
    value: "HP",
    label: "Himachal Pradesh",
    // value: "Himachal Pradesh",
  },
  {
    key: 15,
    value: "JK",
    label: "Jammu and Kashmir",
    // value: "Jammu and Kashmir",
  },
  {
    key: 16,
    value: "JH",
    label: "Jharkhand",
    // value: "Jharkhand",
  },
  {
    key: 17,
    value: "KA",
    label: "Karnataka",
    // value: "Karnataka",
  },
  {
    key: 18,
    value: "KL",
    label: "Kerala",
    // value: "Kerala",
  },
  {
    key: 19,
    value: "LA",
    label: "Ladakh",
    // value: "Ladakh",
  },
  {
    key: 20,
    value: "LD",
    label: "Lakshadweep",
    // value: "Lakshadweep",
  },
  {
    key: 21,
    value: "MP",
    label: "Madhya Pradesh",
    // value: "Madhya Pradesh",
  },
  {
    key: 22,
    value: "MH",
    label: "Maharashtra",
    // value: "Maharashtra",
  },
  {
    key: 23,
    value: "MN",
    label: "Manipur",
    // value: "Manipur",
  },
  {
    key: 24,
    value: "ML",
    label: "Meghalaya",
    // value: "Meghalaya",
  },
  {
    key: 25,
    value: "MZ",
    label: "Mizoram",
    // value: "Mizoram",
  },
  {
    key: 26,
    value: "NL",
    label: "Nagaland",
    // value: "Nagaland",
  },
  {
    key: 27,
    value: "OR",
    label: "Odisha",
    // value: "Odisha",
  },
  {
    key: 28,
    value: "PY",
    label: "Puducherry",
    // value: "Puducherry",
  },
  {
    key: 29,
    value: "PB",
    label: "Punjab",
    // value: "Punjab",
  },
  {
    key: 30,
    value: "RJ",
    label: "Rajasthan",
    // value: "Rajasthan",
  },
  {
    key: 31,
    value: "SK",
    label: "Sikkim",
    // value: "Sikkim",
  },
  {
    key: 32,
    value: "TN",
    label: "Tamil Nadu",
    // value: "Tamil Nadu",
  },
  {
    key: 33,
    value: "TS",
    label: "Telangana",
    // value: "Telangana",
  },
  {
    key: 34,
    value: "TR",
    label: "Tripura",
    // value: "Tripura",
  },
  {
    key: 35,
    value: "UP",
    label: "Uttar Pradesh",
    // value: "Uttar Pradesh",
  },
  {
    key: 36,
    value: "UK",
    label: "Uttarakhand",
    // value: "Uttarakhand",
  },
  {
    key: 37,
    value: "WB",
    label: "West Bengal",
    // value: "West Bengal",
  },
];
